/**
 * content-loader.js
 * Dynamic Markdown content system for stephanebah.github.io
 *
 * Usage:
 *   - Posts:    ContentLoader.loadBlog('#blog-feed')
 *   - Projects: ContentLoader.loadProjects('#projects-grid')
 *   - Single:   ContentLoader.loadPost('slug', '#post-container')
 *   - Single:   ContentLoader.loadProject('slug', '#project-container')
 */

const ContentLoader = (() => {
  const REPO = 'StephaneBah/stephanebah.github.io';
  const BRANCH = 'main';
  const API_BASE = `https://api.github.com/repos/${REPO}/contents`;
  const RAW_BASE = `https://raw.githubusercontent.com/${REPO}/${BRANCH}`;

  // ─── Front Matter Parser ──────────────────────────────────────────────────
  function parseFrontMatter(raw) {
    const match = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
    if (!match) return { meta: {}, content: raw };

    const meta = {};
    match[1].split('\n').forEach(line => {
      const colonIdx = line.indexOf(':');
      if (colonIdx === -1) return;
      const key = line.slice(0, colonIdx).trim();
      let val = line.slice(colonIdx + 1).trim();

      // Parse arrays like ["tag1", "tag2"]
      if (val.startsWith('[')) {
        try {
          val = JSON.parse(val.replace(/'/g, '"'));
        } catch {
          val = val.replace(/[\[\]"']/g, '').split(',').map(s => s.trim());
        }
      } else {
        // Remove surrounding quotes
        val = val.replace(/^["']|["']$/g, '');
      }
      meta[key] = val;
    });

    return { meta, content: match[2].trim() };
  }

  // ─── Fetch directory listing from GitHub API ─────────────────────────────
  async function fetchDirectory(dir) {
    // Try local index.json first (generated by script)
    try {
      const indexRes = await fetch(`${dir}/index.json?nocache=${Date.now()}`);
      if (indexRes.ok) {
        const data = await indexRes.json();
        if (Array.isArray(data)) {
          return data
            .filter(item => {
              const name = typeof item === 'string' ? item : item.name;
              return name && name.endsWith('.md');
            })
            .map(item => typeof item === 'string' ? { name: item } : item);
        }
      }
    } catch (e) {
      console.warn('Local index fetch failed', e);
    }

    try {
      const res = await fetch(`${API_BASE}/${dir}`);
      if (!res.ok) throw new Error(`GitHub API ${res.status}`);
      const files = await res.json();
      return files.filter(f => f.name.endsWith('.md'));
    } catch (err) {
      console.warn('Failed to fetch directory listing.', err);
      return null;
    }
  }

  // ─── Fetch raw markdown content ───────────────────────────────────────────
  async function fetchRaw(path) {
    try {
      const localRes = await fetch(path, { cache: 'no-store' });
      if (localRes.ok) return await localRes.text();
    } catch {
      // Ignore and try remote fallback
    }

    const remoteRes = await fetch(`${RAW_BASE}/${path}`);
    if (!remoteRes.ok) throw new Error(`Failed to fetch ${path}`);
    return await remoteRes.text();
  }

  // ─── Slug from filename ───────────────────────────────────────────────────
  function slugFrom(filename) {
    return filename.replace(/\.md$/, '');
  }

  // ─── Date from post filename (YYYY-MM-DD-slug) ────────────────────────────
  function dateFromPostSlug(slug) {
    const match = slug.match(/^(\d{4}-\d{2}-\d{2})/);
    return match ? match[1] : null;
  }

  // ─── Render Markdown → HTML ───────────────────────────────────────────────
  function renderMarkdown(md) {
    if (window.marked) return marked.parse(md);
    // Minimal fallback if marked.js not loaded
    return md
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/^/, '<p>')
      .replace(/$/, '</p>');
  }

  // ─── Tag chip HTML ────────────────────────────────────────────────────────
  function tagChip(tag) {
    return `<span class="tag-chip">${tag}</span>`;
  }

  // ─── Spinner ─────────────────────────────────────────────────────────────
  function spinner() {
    return `<div class="cl-spinner"><span></span><span></span><span></span></div>`;
  }

  // ─── Error message ────────────────────────────────────────────────────────
  function errorMsg(msg) {
    return `<div class="cl-error"><p>${msg}</p></div>`;
  }

  // ─── Blog card HTML ───────────────────────────────────────────────────────
  function blogCard({ slug, meta }) {
    const date = meta.date || dateFromPostSlug(slug) || '';
    const tags = Array.isArray(meta.tags) ? meta.tags : [];
    const formattedDate = date
      ? new Date(date).toLocaleDateString('fr-FR', { year: 'numeric', month: 'long', day: 'numeric' })
      : '';

    return `
      <article class="blog-card fade-up" data-tags="${tags.join(',').toLowerCase()}">
        <a href="post.html?slug=${slug}" class="blog-card-link">
          <div class="blog-card-meta">
            <span class="blog-date">${formattedDate}</span>
            <span class="blog-read-time">${meta.readTime || '~8'} min</span>
          </div>
          <h3>${meta.title || slug}</h3>
          <p>${meta.description || ''}</p>
          <div class="tag-chips">${tags.map(tagChip).join('')}</div>
          <span class="read-more-arrow">${window.I18n ? window.I18n.tr('blog.read') : 'Lire l\'article →'}</span>
        </a>
      </article>`;
  }

  // ─── Project card HTML ────────────────────────────────────────────────────
  function projectCard({ slug, meta }) {
    const tags = Array.isArray(meta.tags) ? meta.tags : [];
    const date = meta.date
      ? new Date(meta.date).toLocaleDateString('fr-FR', { year: 'numeric', month: 'short' })
      : '';
    const statusClass = meta.status === 'Déployé' ? 'status-live' : 'status-done';

    return `
      <a href="project.html?slug=${slug}" class="project-card fade-up" data-category="${meta.category || 'other'}" data-tags="${tags.join(',').toLowerCase()}">
        ${meta.image ? `<div class="project-card-img"><img src="${meta.image}" alt="${meta.title}" loading="lazy" /></div>` : ''}
        <div class="project-card-body">
          <div class="project-card-top">
            <span class="project-category-tag">${(meta.category || '').toUpperCase()}</span>
            ${meta.status ? `<span class="project-status ${statusClass}">${meta.status}</span>` : ''}
          </div>
          <h3>${meta.title || slug}</h3>
          <p>${meta.description || ''}</p>
          <div class="tag-chips small">${tags.slice(0, 4).map(tagChip).join('')}</div>
          <div class="project-card-footer">
            <span class="card-date">${date}</span>
            ${meta.github ? `<a href="${meta.github}" target="_blank" rel="noopener" class="card-link-icon" onclick="event.stopPropagation()">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
            </a>` : ''}
            ${meta.demo ? `<a href="${meta.demo}" target="_blank" rel="noopener" class="card-link-icon card-link-demo" onclick="event.stopPropagation()">↗</a>` : ''}
          </div>
        </div>
      </a>`;
  }

  // ─── Load blog feed ───────────────────────────────────────────────────────
  async function loadBlog(selector) {
    const container = document.querySelector(selector);
    if (!container) return;

    container.innerHTML = spinner();

    try {
      const files = await fetchDirectory('_posts');
      if (!files || files.length === 0) {
        const msg = window.I18n ? window.I18n.tr('no.posts') : 'Aucun article pour l\'instant. Revenez bientôt !';
        container.innerHTML = errorMsg(msg);
        return;
      }

      // Sort by date descending (filename starts with YYYY-MM-DD)
      files.sort((a, b) => b.name.localeCompare(a.name));

      const posts = await Promise.all(
        files.map(async f => {
          const raw = await fetchRaw(`_posts/${f.name}`);
          const { meta } = parseFrontMatter(raw);
          return { slug: slugFrom(f.name), meta };
        })
      );

      container.innerHTML = posts.map(blogCard).join('');
      initFadeObserver(container);
    } catch (err) {
      container.innerHTML = errorMsg('Contenu temporairement indisponible. Veuillez réessayer.');
      console.error(err);
    }
  }

  // ─── Load projects grid ────────────────────────────────────────────────────
  async function loadProjects(selector) {
    const container = document.querySelector(selector);
    if (!container) return;

    container.innerHTML = spinner();

    try {
      const files = await fetchDirectory('_projects');
      if (!files || files.length === 0) {
        const msg = window.I18n ? window.I18n.tr('no.projects') : 'Aucun projet disponible.';
        container.innerHTML = errorMsg(msg);
        return;
      }

      // Sort by date descending
      const projects = await Promise.all(
        files.map(async f => {
          const raw = await fetchRaw(`_projects/${f.name}`);
          const { meta } = parseFrontMatter(raw);
          return { slug: slugFrom(f.name), meta };
        })
      );

      projects.sort((a, b) => {
        const da = a.meta.date || '0';
        const db = b.meta.date || '0';
        return db.localeCompare(da);
      });

      container.innerHTML = projects.map(projectCard).join('');
      initFadeObserver(container);

      // Wire up filter buttons if present
      initProjectFilter(container);
    } catch (err) {
      container.innerHTML = errorMsg('Contenu temporairement indisponible.');
      console.error(err);
    }
  }

  // ─── Load single post ──────────────────────────────────────────────────────
  async function loadPost(slug, selector) {
    const container = document.querySelector(selector);
    if (!container) return;

    container.innerHTML = spinner();

    try {
      const raw = await fetchRaw(`_posts/${slug}.md`);
      const { meta, content } = parseFrontMatter(raw);
      const tags = Array.isArray(meta.tags) ? meta.tags : [];
      const date = meta.date
        ? new Date(meta.date).toLocaleDateString('fr-FR', { year: 'numeric', month: 'long', day: 'numeric' })
        : '';

      // Update page title
      document.title = `${meta.title || slug} — Stéphane AHOLOU-BAH`;

      container.innerHTML = `
        <header class="post-header">
          <a href="blog.html" class="back-link" data-i18n="back.blog">← Retour aux articles</a>
          <div class="post-meta">
            <span class="blog-date">${date}</span>
            <span class="blog-read-time">${meta.readTime || '~8'} min de lecture</span>
          </div>
          <h1>${meta.title || slug}</h1>
          <p class="post-description">${meta.description || ''}</p>
          <div class="tag-chips">${tags.map(tagChip).join('')}</div>
        </header>
        <div class="post-body markdown-body">
          ${renderMarkdown(content)}
        </div>
        <footer class="post-footer">
          <a href="blog.html" class="back-link" data-i18n="back.blog">← Retour aux articles</a>
        </footer>`;
      // Apply translations to newly rendered content
      if (window.I18n) window.I18n.apply(window.I18n.get());
    } catch (err) {
      container.innerHTML = errorMsg('Article introuvable.');
      console.error(err);
    }
  }

  // ─── Load single project ───────────────────────────────────────────────────
  async function loadProject(slug, selector) {
    const container = document.querySelector(selector);
    if (!container) return;

    container.innerHTML = spinner();

    try {
      const raw = await fetchRaw(`_projects/${slug}.md`);
      const { meta, content } = parseFrontMatter(raw);
      const tags = Array.isArray(meta.tags) ? meta.tags : [];

      document.title = `${meta.title || slug} — Stéphane AHOLOU-BAH`;

      container.innerHTML = `
        <header class="project-detail-header">
          <a href="projects.html" class="back-link" data-i18n="back.projects">← Retour aux projets</a>
          <div class="project-tags">
            <span class="project-category-tag">${(meta.category || '').toUpperCase()}</span>
            ${meta.status ? `<span class="project-status">${meta.status}</span>` : ''}
          </div>
          <h1>${meta.title || slug}</h1>
          <p class="project-subtitle">${meta.description || ''}</p>
          <div class="tag-chips">${tags.map(tagChip).join('')}</div>
          <div class="project-links-header">
            ${meta.github ? `<a href="${meta.github}" target="_blank" rel="noopener" class="btn btn-sm">GitHub →</a>` : ''}
            ${meta.demo ? `<a href="${meta.demo}" target="_blank" rel="noopener" class="btn btn-sm btn-outline">Demo ↗</a>` : ''}
          </div>
        </header>
        <div class="post-body markdown-body">
          ${renderMarkdown(content)}
        </div>
        <footer class="post-footer">
          <a href="projects.html" class="back-link" data-i18n="back.projects">← Retour aux projets</a>
        </footer>`;
      // Apply translations to newly rendered content
      if (window.I18n) window.I18n.apply(window.I18n.get());
    } catch (err) {
      container.innerHTML = errorMsg('Projet introuvable.');
      console.error(err);
    }
  }

  // ─── Intersection Observer for fade-up animations ─────────────────────────
  function initFadeObserver(root) {
    const items = (root || document).querySelectorAll('.fade-up');
    if (!items.length) return;

    const observer = new IntersectionObserver(
      entries => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            entry.target.classList.add('visible');
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.1 }
    );

    items.forEach(el => observer.observe(el));
  }

  // ─── Project filter wiring ─────────────────────────────────────────────────
  function initProjectFilter(gridContainer) {
    const buttons = document.querySelectorAll('.filter-btn');
    if (!buttons.length) return;

    buttons.forEach(btn => {
      btn.addEventListener('click', () => {
        buttons.forEach(b => b.classList.remove('active'));
        btn.classList.add('active');

        const filter = btn.dataset.filter;
        const cards = gridContainer.querySelectorAll('.project-card');

        cards.forEach(card => {
          const match = filter === 'all' || card.dataset.category === filter;
          card.style.display = match ? '' : 'none';
          if (match) card.classList.add('visible');
        });
      });
    });
  }

  // ─── Public API ───────────────────────────────────────────────────────────
  return {
    loadBlog,
    loadProjects,
    loadPost,
    loadProject,
    initFadeObserver,
    parseFrontMatter,
  };
})();

// Auto-init fade observer on regular elements when DOM ready
document.addEventListener('DOMContentLoaded', () => {
  ContentLoader.initFadeObserver(document);
});
